server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://192.168.40.150:3306/xxxx?useUnicode=true&amp;characterEncoding=utf8&amp;useSSL=false
      password: 11111
      username: root
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

  dubbo:
    appname: quiz-uid
    port: 20880
    registry: zookeeper://192.168.40.140:2181
    server: true

mybatis:
  mapper-locations: classpath:/META-INF/mybatis/mapper/*.xml
  type-aliases-package: com.baidu.fsg.uid.worker.entity
  


